package com.journal.hibernate.model;
// default package
// Generated Oct 7, 2015 9:13:05 PM by Hibernate Tools 4.3.1.Final

/**
 * Customer generated by hbm2java
 */
public class Customer{
private long id;
	private String name;
	private String email;
	private String address;

	private Txn txn;
	
	
	private long getId;
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Txn getTxn() {
		return txn;
	}

	public void setTxn(Txn txn) {
		this.txn = txn;
	}

	

}
